stateDiagram-v2

     [*] --> on_activation
     [*] --> on_inactivation

     on_activation: get_local_position
     on_activation: get_position_setpoint_triplet

     on_activation --> on_active : while get new target measurement


     State on_active {

        [*] --> start
        State start
            start: run_state_start
        State HorizontalApproach
            HorizontalApproach: run_state_horizontal_approach
        State DescendAboveTarget
            DescendAboveTarget: run_state_descend_above_target
        State FinalApproach
            FinalApproach: run_state_final_approach
        State Search
            Search: run_state_search
        State Fallback
            Fallback: run_state_fallback
        State YawAlignment
            YawAlignment: run_state_yaw_alignment
        State Done
            Done: run_state_done

        start : check_state_conditions, reset search attempts

        start --> Search: in Conditional mode Search while descending in current location
        Search --> HorizontalApproach: if target visible and stay for 1s and under PLD_SRCH_ALT
        Search --> Fallback: if target not visible for PLD_SRCH_TOUT or if PLD_MAX_SRCH attempts were made

        Search: check_state_conditions
        HorizontalApproach : check_state_conditions
        DescendAboveTarget: check_state_conditions
        FinalApproach: check_state_conditions

        HorizontalApproach --> YawAlignment: if target in PLD_HACC_RAD
        HorizontalApproach --> Fallback: if marker position not reached for PLD_HA_TOUT
        HorizontalApproach --> Search : if target lost

        YawAlignment --> DescendAboveTarget: if heading reached or PLD_YAW_TOUT passed

        DescendAboveTarget --> FinalApproach : if PLD_FAPPR_ALT reached
        DescendAboveTarget --> Search: if target lost
        FinalApproach --> Done : check_state_conditions

        Fallback --> NormalLand

        }
