name: Makefile CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  doc-build:

    runs-on: [self-hosted, X64]
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        repository: BeagleSystems/BeagleComrade
        path: ~/BeagleComrade
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Python3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Get msg definitions for BeagleComrade
      run: vcs import ~/BeagleComrade/src < ~/BeagleComrade/src/.rosinstall

    - name: Build docs
      run: make clean && make html
