name: Makefile CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  doc-build:

    runs-on: [self-hosted, DOCHOST]
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        repository: BeagleSystems/mavros
        ref: develop
        path: mavros
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        repository: BeagleSystems/ros_precland
        ref: develop
        path: ros_precland
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Python3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Build docs
      run: make clean && make html && make 
