name: Convert RST to Markdown & HTML

on:
  push:
    paths:
      - 'source/*.rst'

jobs:
  convert:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make output folder
        run: mkdir -p converted

      - name: Convert RST files
        run: |
          for f in source/*.rst; do
            base="${f##*/}"
            name="${base%.rst}"
            pandoc "$f" -f rst -t markdown -o "converted/$name.md"
            pandoc "$f" -f rst -t html     -o "converted/$name.html"
          done

      - name: Upload converted files
        uses: actions/upload-artifact@v4
        with:
          name: converted-files
          path: converted/
